# -*- coding: utf-8 -*-
"""Sude Mengen - Pizza Sipariş Sistemi.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14NRBTCaMPiWRg-LZQyj59AGoj4KIGVAb
"""

# Sude Mengen - Pizza Sipariş Sistemi (projemde bazı eksiklikler var, phyton'ı bu bootcamp ile öğrendim.
# Elimden geleni yaptım, sadece fiyatı yazdıramadım.)
# Gerekli kütüphaneleri yükledim
import csv
import datetime

# Menu.txt dosyası yaptım ve yükledim.
f = open("/Menu/Menu.txt", "r")
print(f.read())

# Pizza üst sınıf oluşturdum.
class Pizza:
    price: float
    def __init__(self):
        self.name = ""
        self.price = 0.0

    def get_description(self):
        return self.name
        Pizza.get_description(self)

    def get_cost(self):
        return self.price
        Pizza.get_cost(self)

# Alt sınıf oluşturup pizzaların özelliklerini yazıyorum.
class KlasikPizza(Pizza):
    def __init__(self):
        super().__init__()
        self.name = "Klasik Pizza Malzemeleri: Kaşar Peyniri, Sucuk, Biber"
        self.cost = 65.0
        print(self.name, "→", self.cost, "TL")


class MargaritaPizza(Pizza):
    def __init__(self):
        super().__init__()
        self.name = "Margarita Pizza Malzemeleri: Fesleğen, Mozerella Peyniri, Domates"
        self.cost = 70.0
        print(self.name, "→", self.cost, "TL")


class TurkPizza(Pizza):
    def __init__(self):
        super().__init__()
        self.name = "Türk Pizza Malzemeleri: Sarımsak, Pastırma, Kıyma, Kekik"
        self.cost = 85.0
        print(self.name, "→", self.cost, "TL")


class SadePizza(Pizza):
    def __init__(self):
        super().__init__()
        self.name = "Sade Pizza Malzemeleri: Salam, Özel Sos, Baharat"
        self.cost = 50.0
        print(self.name, "→", self.cost, "TL")


# Pizza decorator üst sınıf oluşturdum.
class PizzaDecorator(Pizza):
    def __init__(self, toppings):
        super().__init__()
        self.toppings = toppings

    def get_description(self):
        return self.toppings.get_description() + ' :' + Pizza.get_description(self)

    def get_cost(self):
        return self.toppings.get_cost() + ' =' + Pizza.get_cost(self)


# Pizza decorator alt sınıfları oluşturdum.
class Zeytin(PizzaDecorator):
    def __init__(self, toppings):
        super().__init__(toppings)
        self.toppings = toppings
        self.name = "Zeytin"
        self.cost = 5.0
        print(self.name, "→", self.cost, "TL")


class Mantar(PizzaDecorator):
    def __init__(self, toppings):
        super().__init__(toppings)
        self.toppings = toppings
        self.name = "Mantar"
        self.cost = 6.0
        print(self.name, "→", self.cost, "TL")


class KeciPeyniri(PizzaDecorator):
    def __init__(self, toppings):
        super().__init__(toppings)
        self.toppings = toppings
        self.name = "Keçi Peyniri"
        self.cost = 3.0
        print(self.name, "→", self.cost, "TL")


class Et(PizzaDecorator):
    def __init__(self, toppings):
        super().__init__(toppings)
        self.toppings = toppings
        self.name = "Et *en çok tercih edilen malzememiz*"
        self.cost = 15.0
        print(self.name, "→", self.cost, "TL")


class Sogan(PizzaDecorator):
    def __init__(self, toppings):
        super().__init__(toppings)
        self.toppings = toppings
        self.name = "Soğan"
        self.cost = 2.0
        print(self.name, "→", self.cost, "TL")


class Misir(PizzaDecorator):
    def __init__(self, toppings):
        super().__init__(toppings)
        self.toppings = toppings
        self.name = "Mısır"
        self.cost = 5.0
        print(self.name, "→", self.cost, "TL")


class EkMalzemesiz(PizzaDecorator):
    def __init__(self, toppings):
        super().__init__(toppings)
        self.toppings = toppings
        self.name = "Ek Malzemesiz"
        self.cost = 0.0
        print(self.name, "→", self.cost, "TL")

#Sipariş için gereken bilgileri oluşturdum.
def orders_informations():
    name1 = input("Lütfen adınızı ve soyadınızı giriniz: ")

    ID = ""
    while ID == "":
        ID = input("11 haneli TC Kimlik numaranızı giriniz: ")
        if len(ID) != 11:
            print("Lütfen TC Kimlik numaranızı 11 haneli giriniz.")
            ID = ""

    card_no = ""
    while card_no == "":
        card_no = input("16 haneli kart numaranızı giriniz: *Lütfen boşluk bırakmadan ve karakter kullanmadan giriniz.* ")
        if len(card_no) != 16:
            print("Lütfen kart numaranızı 16 haneli giriniz.")
            card_no = ""

    card_password = ""
    while card_password == "":
        card_password = input("4 haneli kart şifrenizi giriniz: ")
        if len(card_password) != 4:
            print("Lütfen kart şifrenizi 4 haneli giriniz.")
            card_password = ""

        print("Siparişiniz alınmıştır.")
        print(datetime.datetime.now())

    time_of_order = datetime.datetime.now()
    return name1, ID, card_no, card_password, time_of_order

# Csv'yi kuruyorum:
def csv_file():
    with open("Orders_Database.csv", 'r') as csv_file:
        reader = csv.reader(csv_file)
        for row in reader:
            print(row)
        csv_file.close()

# Sipariş ekranındaki pizza seçimlerini ayrıntılı işlemek istedim. Main fonksiyonu oluşturdum.
def main():
    name = ""
    while name == "":
        name = input("Hoş geldiniz! Lütfen pizzanızı seçiniz: ")
        if name == "1":
            name = KlasikPizza()
            print("--Klasik Pizza seçimini yaptınız.")
        elif name == "2":
            name = MargaritaPizza()
            print("--Margarita Pizza seçimini yaptınız.")
        elif name == "3":
            name = TurkPizza()
            print("--Türk Pizza seçimini yaptınız.")
        elif name == "4":
            name = SadePizza()
            print("--Sade Pizza seçimini yaptınız.")
        else:
            print("Lütfen doğru seçiniz!")
            name = ""

# Pizza ek malzemesi:
    toppings = ""
    while toppings == "":
        toppings = input("Lütfen pizzanız için ekstra malzeme seçiniz: ")
        if toppings == "5":
            toppings = Zeytin(PizzaDecorator)
            print("--Ek malzeme olarak Zeytin seçtiniz.")
        elif toppings == "6":
            toppings = Mantar(PizzaDecorator)
            print("--Ek malzeme olarak Mantar seçtiniz.")
        elif toppings == "7":
            toppings = KeciPeyniri(PizzaDecorator)
            print("--Ek malzeme olarak Keçi Peyniri seçtiniz.")
        elif toppings == "8":
            toppings = Et(PizzaDecorator)
            print("--Ek malzeme olarak Et seçtiniz.")
        elif toppings == "9":
            toppings = Sogan(PizzaDecorator)
            print("--Ek malzeme olarak Soğan seçtiniz.")
        elif toppings == "10":
            toppings = Misir(PizzaDecorator)
            print("--Ek malzeme olarak Mısır seçtiniz.")
        elif toppings == "11":
            toppings = EkMalzemesiz(PizzaDecorator)
            print("--Ek malzeme istemediniz.")
        else:
            print("Lütfen doğru seçiniz!")
            toppings = ""
    return orders_informations()
main()